version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:edge
      resource_class: medium
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
    
      # deploy the image
      - run:
          command: docker run -p 80:80 zodinx/newbiee7:latest
          no_output_timeout: 1h
